site_name: "nb_prep"
site_description: "Prepare jupyter notebooks for storing in git and sharing as HTML"
edit_uri: ''
copyright: 'Copyright &copy; 2022'
repo_url: https://github.com/allianz-direct/nb_prep

nav:
  - index.md
  - usage.md
  - options.md

theme:
    name: material
    custom_dir: docs/overrides
    icon:
        logo: material/notebook-check-outline
        repo: fontawesome/brands/github
    features:
        - content.tabs.link
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections
        - navigation.expand
    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
          primary: blue
          accent: blue
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
          primary: blue
          accent: blue

plugins:
  - search
  - git-authors:
        exclude:
            - index.md
  - git-revision-date-localized:
      type: timeago
      timezone: Europe/Amsterdam
      locale: en
      fallback_to_build_date: false
      enable_creation_date: false

markdown_extensions:
    - meta
    - admonition
    - pymdownx.keys
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.tabbed:
        alternate_style: true 
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
          options:
              custom_icons:
                  - site/overrides/.icons