name: Unit tests
on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main
jobs:
  run:
    name: Run unit tests
    runs-on: ${{ matrix.os }}
    env:
      USING_COVERAGE: '3.7'
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9, "3.10"]
    steps:
    - uses: actions/checkout@master

    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install --upgrade setuptools
        pip3 install --upgrade wheel
        pip3 install pyflakes
        pip3 install -r tests/test_requirements.txt
        pip3 install .

    - name: Static code checking with pyflakes
      run: |
        pyflakes nb_prep

    - name: Run unit tests
      run: |
        git config --global user.name "Github Action"
        git config --global user.email "githubaction@gmail.com"
        pytest --cov=nb_prep
  